{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cnf1.serviceAccountName" . }}
  namespace: default
  labels:
{{ include "cnf1.labels" . | nindent 4 }}
{{- end -}}
